development:
  adapter: postgresql
  encoding: unicode
  database: rabbitmq_consumer_development_<%= ENV['QUEUE_ID'] %>
  pool: 5
  min_messages: notice

test:
  adapter: postgresql
  encoding: unicode
  database: rabbitmq_consumer_test_<%= ENV['QUEUE_ID'] %>
  pool: 5
  min_messages: notice

production:
  adapter: postgresql
  encoding: unicode
  database: rabbitmq_consumer_development_<%= ENV['QUEUE_ID'] %>
  pool: 5
  min_messages: notice
